baseURL = "https://gitjoin.com/"
title   = "gitjoin — Virtual monorepo made simple."

disableKinds = [
    "taxonomy",
    "term",
    "404",
    "page",
    "robotstxt",
    "rss",
    "section",
    "sitemap",
]

[params]
  description = "gitjoin turns many repositories into one virtual monorepo. Minimal config, no rewrites of history."
  repoURL     = "https://github.com/bep/gitjoin"
